Marshal.dump(aFloat) crash when $DEBUG = true
% jruby164 -e 'Marshal.dump(0.0)'
% jruby164 -e 'p Marshal.dump(0.0)'
"\004\bf\0060"
% jruby164 -d -e 'p Marshal.dump(0.0)'
ArgumentError: too many arguments for format string
    dump at org/jruby/RubyMarshal.java:101
  (root) at -e:1

It's from 2010-12-28.
spec/regression/JRUBY-4335_float_marshal_roundtrip_spec.rb started to
fail recently because of this.

commit ab3899a959209725904845a101d703a244b25279
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Tue Dec 28 16:04:38 2010 -0600

    Fix marshalled Float format to match Ruby. JRUBY-4334 and
JRUBY-4335.