Add opens for java.io and java.nio.channels to improve compat.
These packages are reflected against so heavily and for so many
low-level Ruby compatibility features that we're opening them up
for now. This was forced because we load some extensions through
a URLClassLoader, and it appears that URLClassLoader-ed libraries
get stricter treatment when it comes to illegal accesess.

The following error resulted from Puma without the java.io opens:

```
=> Booting Puma
=> Rails 5.2.1 application starting in development
=> Run `rails server -h` for more startup options
Exiting
LoadError: load error: puma/java_io_buffer -- java.lang.reflect.InaccessibleObjectException: Unable to make field protected byte[] java.io.ByteArrayOutputStream.buf accessible: module java.base does not "opens java.io" to module org.jruby.dist
          require at org/jruby/RubyKernel.java:976
          require at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287
  load_dependency at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253
          require at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287
           <main> at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/io_buffer.rb:4
```