Fixes to support newer JRuby when using gem plugin
9.2.11.1 appeared to cause some issues resulting in the following
error:

```
INFO] --- gem-maven-plugin:1.0.7:initialize (default-initialize) @ jruby-jars ---
Downloading from mavengems: mavengem:https://rubygems.org/org/jruby/jruby-complete/9.2.11.1/jruby-complete-9.2.11.1.jar
LoadError: no such file to load -- rubygems/defaults/jruby
  require at org/jruby/RubyKernel.java:1071
   (root) at <script>:1
```

I believe the change here fixes this problem, since there's no
need to explicitly require the JRuby defaults file for RubyGems.

The jruby-jars change uses a 9.3 snapshot to pick up this change.
We will want to change it to 9.3.0.0 non-snapshot when it is
released.