[refactor] redundant comparison for int
error: [ComparisonOutOfRange] ints may have a value in the range
-2147483648 to 2147483647; therefore, this comparison to 0x7fffffff will
always evaluate to true