Update test.rake option
When test:mri:core:int or test:mri:core:jit run, many NoMethodError occurs.
```
NoMethodError: undefined method `formatter' for DidYouMean:Module
```
This commit removes --disable-gem option from test.rake file because test/mir/ruby/test_pattern_match.rb requires DidYouMean module.