Fix for JRUBY-2699: If user's PATH contains '.' and 'jruby' resolves to './jruby', JRUBY_HOME is incorrectly set to '.', leading to 'NoClassDefFoundError'
git-svn-id: http://svn.codehaus.org/jruby/trunk/jruby@9064 961051c9-f516-0410-bf72-c9f7e237a7b7