JRUBY-4717: Import digest.rb from CRuby stdlib.
I broke digest lib for 1.8 at 51bf9d9f and Nick fixed it at 288ef4ae.
And this is a new try for re-fixing digest library for JRUBY-4717.

 * Update tool/globals_1_8_7.rb to import digest.rb for 1.8 as same as
   1.9.
 * Remove Java implementation of Digest.const_missing. It's defined in
   lib/digest.rb for both 1.8 and 1.9.
 * Revert 288ef1ae. It does not mean that 288ef4ae is wrong. It's
   51bf9d9f which should be fixed and needs above fixes. 288ef4ae was
   needed.

With importing lib/digest.rb for 1.8 mode, Digest function start working
for 1.8 as same as CRuby.

% ruby187 -rdigest -e 'p Digest("SHA2")'
Digest::SHA2

% jruby -rdigest -e 'p Digest("SHA2")'
Digest::SHA2

% jruby163 -rdigest -e 'p Digest("SHA2")'
NoMethodError: undefined method `Digest' for main:Object
  (root) at -e:1