argument parameters use bytelist now (mostly).  This allows stuff like:
```text
jruby -e 'p method(def foo(あ); end).parameters'
[[:req, :あ]]
```

to work.  Up til now this would confuse our impl and we may see an error like:

```text
ArgumentError: invalid byte sequence in US-ASCII
  inspect at org/jruby/RubySymbol.java:283
  inspect at org/jruby/RubySymbol.java:268
  inspect at org/jruby/RubyArray.java:1659
  inspect at org/jruby/RubyArray.java:1659
        p at org/jruby/RubyKernel.java:492
   <main> at -e:1
```

Pure ruby code should not properly be giving properly encoded values back. Java
(e.g. native) methods mostly should not matter since they do not return names
but if they do return names then they are all assumed to be UTF-8 encoded data.